In [32]:
import pandas as pd  
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import seaborn as sns
import random

In [33]:
df = pd.read_csv(r"C:\Users\rohan\Electricity Demand Prediction Machine Learning Model\Electricity+Demand+Dataset.csv")
df.head()

,Timestamp,hour,dayofweek,month,year,dayofyear,Temperature,Humidity,Demand
0,01-Jan-20,0.0,2.0,1.0,2020.0,1.0,3.000000,61.288951,2457.119872
1,01-Jan-20,1.0,2.0,1.0,2020.0,1.0,3.000000,52.873702,2269.904712
2,01-Jan-20,2.0,2.0,1.0,2020.0,1.0,4.244482,36.341783,2215.640403
3,01-Jan-20,3.0,2.0,1.0,2020.0,1.0,3.000000,72.629378,2174.232413
4,01-Jan-20,4.0,2.0,1.0,2020.0,1.0,3.881208,90.582444,2472.453006

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43848 entries, 0 to 43847
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Timestamp    43848 non-null  object
 1   hour         43837 non-null  float64
 2   dayofweek    43839 non-null  float64
 3   month        43840 non-null  float64
 4   year         43843 non-null  float64
 5   dayofyear    43843 non-null  float64
 6   Temperature  43841 non-null  float64
 7   Humidity     43838 non-null  float64
 8   Demand       43841 non-null  float64
dtypes: float64(8), object(1)
memory usage: 3.0+ MB

In [35]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

C:\Users\rohan\AppData\Local\Temp\ipykernel_10452\766710655.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43848 entries, 0 to 43847
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Timestamp    43848 non-null  datetime64[ns]
 1   hour         43837 non-null  float64
 2   dayofweek    43839 non-null  float64
 3   month        43840 non-null  float64
 4   year         43843 non-null  float64
 5   dayofyear    43843 non-null  float64
 6   Temperature  43841 non-null  float64
 7   Humidity     43838 non-null  float64
 8   Demand       43841 non-null  float64
dtypes: datetime64[ns](1), float64(8)
memory usage: 3.0 MB

In [37]:
df =df.set_index('Timestamp')

In [38]:
df

,hour,dayofweek,month,year,dayofyear,Temperature,Humidity,Demand
Timestamp,,,,,,,,
2020-01-01,0.0,2.0,1.0,2020.0,1.0,3.000000,61.288951,2457.119872
2020-01-01,1.0,2.0,1.0,2020.0,1.0,3.000000,52.873702,2269.904712
2020-01-01,2.0,2.0,1.0,2020.0,1.0,4.244482,36.341783,2215.640403
2020-01-01,3.0,2.0,1.0,2020.0,1.0,3.000000,72.629378,2174.232413
2020-01-01,4.0,2.0,1.0,2020.0,1.0,3.881208,90.582444,2472.453006
...,...,...,...,...,...,...,...,...
2024-12-31,19.0,1.0,12.0,2024.0,366.0,3.956838,43.287161,4689.693109
2024-12-31,20.0,1.0,12.0,2024.0,366.0,3.118824,51.705756,4331.249224
2024-12-31,21.0,1.0,12.0,2024.0,366.0,3.000000,40.565916,4015.979957
2024-12-31,22.0,1.0,12.0,2024.0,366.0,3.000000,51.998107,3353.241682
2024-12-31,23.0,1.0,12.0,2024.0,366.0,6.037472,59.931925,3219.023339

In [39]:
df[['Temperature', 'Humidity', 'Demand']].describe()

        Temperature      Humidity        Demand
count  43841.000000  43838.000000  43841.000000
mean      25.067788     59.903007   5000.790976
std       12.821725     18.342604   1412.527409
min        3.000000     20.000000   1611.954020
25%       15.210186     46.241224   4015.668472
50%       25.003212     59.986720   5013.053367
75%       34.740971     73.796820   6000.803082
max       50.000000     95.000000  11910.705100

DATA CLEANING

In [40]:
#to check is thhere any null value in the dataset
df.isnull().sum()

hour           11
dayofweek       9
month           8
year            5
dayofyear       5
Temperature     7
Humidity       10
Demand          7
dtype: int64

In [41]:
#to show the records of null value present in dataset  
df[df.isnull().any(axis=1)]

,hour,dayofweek,month,year,dayofyear,Temperature,Humidity,Demand
Timestamp,,,,,,,,
2020-04-30,NaN,3.0,4.0,2020.0,121.0,21.820261,41.353675,5393.127681
2020-07-21,NaN,1.0,7.0,2020.0,203.0,36.555833,62.779665,6248.349423
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-27,NaN,5.0,2.0,2021.0,58.0,24.001003,53.303268,4523.253789
2021-12-13,23.0,0.0,12.0,2021.0,NaN,3.000000,75.457130,3225.225822
2021-12-14,NaN,1.0,12.0,2021.0,348.0,5.061319,47.215825,2887.848612
2021-12-14,14.0,1.0,12.0,2021.0,348.0,15.403995,74.011557,NaN
2022-06-17,13.0,4.0,6.0,2022.0,168.0,NaN,43.171391,7196.200962
2022-06-17,NaN,4.0,6.0,2022.0,168.0,42.924693,43.645711,7605.572464
2022-06-17,17.0,4.0,NaN,2022.0,168.0,37.115634,37.554842,7696.863268
2022-06-17,18.0,4.0,6.0,2022.0,168.0,39.886471,NaN,7830.425508
2022-06-17,21.0,NaN,6.0,2022.0,168.0,28.471494,54.964101,6408.288394
2022-06-18,5.0,5.0,6.0,2022.0,169.0,38.349174,58.285814,NaN
2023-08-30,NaN,2.0,8.0,2023.0,242.0,25.707715,69.868663,5983.808425
2023-08-31,0.0,NaN,8.0,2023.0,243.0,22.705122,81.691817,4307.378161
2023-08-31,5.0,3.0,NaN,2023.0,243.0,29.081792,81.270824,5181.232963
2023-08-31,11.0,3.0,8.0,NaN,243.0,44.270455,75.563954,6449.406302
2023-08-31,14.0,3.0,8.0,2023.0,243.0,NaN,NaN,7082.853450
2024-01-27,19.0,5.0,1.0,2024.0,27.0,14.351975,NaN,NaN
2024-01-28,2.0,NaN,1.0,2024.0,28.0,3.000000,68.899943,2097.117994
2024-01-28,NaN,6.0,1.0,2024.0,28.0,9.081186,78.163106,3665.332955
2024-09-24,19.0,NaN,9.0,2024.0,268.0,25.632052,74.123843,6221.030041
2024-09-24,21.0,1.0,9.0,2024.0,268.0,19.380978,NaN,5333.268985
2024-09-24,22.0,1.0,9.0,2024.0,268.0,NaN,66.618690,4388.124735
2024-09-25,7.0,2.0,NaN,2024.0,269.0,31.190258,95.000000,5959.811294
2024-12-18,11.0,2.0,12.0,2024.0,353.0,23.075591,NaN,4672.011329
2024-12-18,12.0,2.0,12.0,2024.0,353.0,20.012449,NaN,4743.652853
2024-12-18,21.0,NaN,NaN,2024.0,353.0,3.000000,64.041109,4133.304646

In [42]:
# showing the  data which has all null value  
df[df.isnull().all(axis=1)]

,hour,dayofweek,month,year,dayofyear,Temperature,Humidity,Demand
Timestamp,,,,,,,,
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# we will drop all values which contains null value
df =df.dropna(how='all')

In [44]:
df

,hour,dayofweek,month,year,dayofyear,Temperature,Humidity,Demand
Timestamp,,,,,,,,
2020-01-01,0.0,2.0,1.0,2020.0,1.0,3.000000,61.288951,2457.119872
2020-01-01,1.0,2.0,1.0,2020.0,1.0,3.000000,52.873702,2269.904712
2020-01-01,2.0,2.0,1.0,2020.0,1.0,4.244482,36.341783,2215.640403
2020-01-01,3.0,2.0,1.0,2020.0,1.0,3.000000,72.629378,2174.232413
2020-01-01,4.0,2.0,1.0,2020.0,1.0,3.881208,90.582444,2472.453006
...,...,...,...,...,...,...,...,...
2024-12-31,19.0,1.0,12.0,2024.0,366.0,3.956838,43.287161,4689.693109
2024-12-31,20.0,1.0,12.0,2024.0,366.0,3.118824,51.705756,4331.249224
2024-12-31,21.0,1.0,12.0,2024.0,366.0,3.000000,40.565916,4015.979957
2024-12-31,22.0,1.0,12.0,2024.0,366.0,3.000000,51.998107,3353.241682
2024-12-31,23.0,1.0,12.0,2024.0,366.0,6.037472,59.931925,3219.023339

In [45]:
df.isnull().sum()

hour           7
dayofweek      5
month          4
year           1
dayofyear      1
Temperature    3
Humidity       6
Demand         3
dtype: int64

In [46]:
#chhecking any null value missed or not
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [hour, dayofweek, month, year, dayofyear, Temperature, Humidity, Demand]
Index: []

In [47]:
df.shape

(43844, 8)

Backward Fill -bfill
Forward Fill -ffill

In [48]:
df[['hour','dayofweek','month','year','dayofyear']]= df[['hour','dayofweek','month','year','dayofyear']].ffill()

C:\Users\rohan\AppData\Local\Temp\ipykernel_10452\3352106242.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['hour','dayofweek','month','year','dayofyear']]= df[['hour','dayofweek','month','year','dayofyear']].ffill()

In [49]:
df[['Temperature', 'Humidity', 'Demand']]=df[['Temperature', 'Humidity', 'Demand']].bfill()

C:\Users\rohan\AppData\Local\Temp\ipykernel_10452\3471577007.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Temperature', 'Humidity', 'Demand']]=df[['Temperature', 'Humidity', 'Demand']].bfill()

In [50]:
df['Demand']=df['Demand'].interpolate(method='time')

C:\Users\rohan\AppData\Local\Temp\ipykernel_10452\823444295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Demand']=df['Demand'].interpolate(method='time')

In [51]:
df.isnull().sum()

hour           0
dayofweek      0
month          0
year           0
dayofyear      0
Temperature    0
Humidity       0
Demand         0
dtype: int64

In [52]:
#shhape of dataframe  
df.shape

(43844, 8)